config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources 'messages_head', only: [:index] do
    get 'message_rejects', on: :collection
    get 'message_proposals', on: :collection
  end
  resources :profiles, only: [:new, :create, :show] do
    resources 'messages', only: [:index] do
      get 'message_rejects', on: :collection
      get 'message_proposals', on: :collection
    end
  end
  resources :vacuancy_jobs, only: [:index, :new, :create, :show, :update] do
    get 'search_candidate', on: :collection
    get 'search_headhunter', on: :collection
    resources :comment_of_rejects, only: [:new, :create]
    resources :comment_of_proposals, only: [:new, :create, :edit, :update]
  end
  resources :job_applications, only: [:index, :new, :create, :show, :destroy]
  resources :comment_of_profiles, only: [:create]
  resources :favorites, only: [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if user_signed_in?
      if policy(current_user).user_candidate? && current_user.profile.present?
        @profile = Profile.find(current_user.id)
      else
        @user = current_user
      end
    end
  end
end

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="text-center">
    <h1 class="display-1">Headhunter Web</h1>
    <h1>Seja bem-vindo</h1>
  </div>
</div>

<div class="container">
  <% if user_signed_in? %>
    <div class="row">
      <div class="col">
        <ul class="nav flex-column">
          <% if policy(current_user).user_headhunter? %>
            <li claass="nav-item">
              <%= link_to 'Cadastrar vagas', new_vacuancy_job_path, class: "nav-link" %>
            </li>

            <li claass="nav-item">
              <%= link_to 'Minhas vagas', search_headhunter_vacuancy_jobs_path, class: "nav-link" %>
            </li>

            <% if @user.vacuancy_jobs.present? %>
              <li claass="nav-item">
                <%= link_to Profile.human_attribute_name('messages'), messages_head_index_path, 
                    class: "nav-link" %>
              </li>
            <% else %>
              <li claass="nav-item">
                <%= link_to Profile.human_attribute_name('messages'), messages_head_index_path, 
                    class: "nav-link disabled" %>
              </li>
            <% end %>
          <% end %>

          <% if policy(current_user).user_candidate? %>
            <li claass="nav-item">
              <%= link_to 'Minhas inscrições', search_candidate_vacuancy_jobs_path, class: "nav-link" %>
            </li>

            <% if current_user.profile.present? %>
              <li claass="nav-item">
                <%= link_to Profile.human_attribute_name('messages'), profile_messages_path(@profile), 
                    class: "nav-link" %>
              </li>
            <% end %>
          <% end %>

          <li claass="nav-item">
            <%= link_to 'Vagas de emprego', vacuancy_jobs_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</div>