config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources 'messages_head', only: [:index] do
    get 'message_rejects', on: :collection
    get 'message_proposals', on: :collection
  end
  resources :profiles, only: [:new, :create, :show] do
    resources 'messages', only: [:index] do
      get 'message_rejects', on: :collection
      get 'message_proposals', on: :collection
    end
  end
  resources :vacuancy_jobs, only: [:index, :new, :create, :show, :update] do
    get 'search_candidate', on: :collection
    get 'search_headhunter', on: :collection
    resources :comment_of_rejects, only: [:new, :create]
    resources :comment_of_proposals, only: [:new, :create, :edit, :update]
  end
  resources :job_applications, only: [:index, :new, :create, :show, :destroy]
  resources :comment_of_profiles, only: [:create]
  resources :favorites, only: [:create]
end

app/models/vacuancy_job.rb
class VacuancyJob < ApplicationRecord
  belongs_to :user
  has_many :job_applications
  has_many :comment_of_rejects
  has_many :comment_of_proposals
  enum status: { active: 0, closed: 1 }
end

app/controllers/vacuancy_jobs_controller.rb
class VacuancyJobsController < ApplicationController
  before_action :authenticate_headhunter, only: %i[new create search_headhunter]
  before_action :authenticate_cadidate_profile
  before_action :authenticate_candidate, only: %i[search_candidate]

  def index
    @vacuancy_jobs = VacuancyJob.all
  end

  def new
    @vacuancy_job = VacuancyJob.new
    set_level_selection
  end

  def create
    @vacuancy_job = VacuancyJob.new(params_vacuancy_job)
    set_user_id
    if @vacuancy_job.save
      flash[:notice] = 'Vaga criada com sucesso'
      redirect_to @vacuancy_job
    else
      render 'new'
    end
  end

  def show
    set_job_applications
    set_vacuancy_job
    set_level_selection
    set_user_have_application
  end

  def search_candidate
    @job_applications = JobApplication.where({ user_id: current_user.id })
  end

  def search_headhunter
    @vacuancy_jobs = VacuancyJob.where({ user_id: current_user.id })
  end

  def update
    set_vacuancy_job
    @status = 'closed'
    if @vacuancy_job.update!(status: @status)
      flash[:alert] = 'Fechado com sucesso.'
      redirect_to @vacuancy_job
    else
      flash[:notice] = 'Algo deu errado.'
      render root_path
    end
  end

  private

  def params_vacuancy_job
    params.require(:vacuancy_job).permit(:title, :description,
                                         :ability_description, :initial_salary,
                                         :end_salary, :level, :limit_date,
                                         :addresse)
  end

  def set_user_id
    @vacuancy_job.user = current_user
  end

  def set_level_selection
    @level_selection = [['Estágio', 0], ['Junior', 1], ['Pleno', 2],
                        ['Sênior', 3], ['Especialista', 4], ['Diretor', 5]]
  end

  def set_vacuancy_job
    @vacuancy_job = VacuancyJob.find(params[:id])
  end

  def set_job_applications
    @job_applications = JobApplication.where("vacuancy_job_id = #{params[:id]}")
  end

  def set_user_have_application
    user = current_user
    @application = false
    @job_applications.each do |job_application|
      if job_application.user_id == user.id
        return @application = true
      end
    end
  end
end

app/views/vacuancy_jobs/_vagas.html.erb
<div class="row">
  <div class="col-sm-5">
    <% @vacuancy_jobs.each do |vacuancy_job| %>
      <% if vacuancy_job.status == 'active' %>
        <div class="card">
          <div class="card-body">
            <h3 class="card-title"><%= link_to vacuancy_job.title, vacuancy_job_path(vacuancy_job) %></h3>
            <p class="card-text"><%= vacuancy_job.description %></p>
          </div>
        </div>
        <br/>
      <% end %>
    <% end %>
  </div>
</div>

app/views/vacuancy_jobs/index.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="display-3">Vagas de Emprego</h1>
    <br/>
  </div>

  <%= render partial: 'vagas' %>

  <div class="actions">
    <br/>
    <%= link_to Profile.human_attribute_name('back'), :back, class: "btn btn-dark" %>
  </div>
</div>

app/views/vacuancy_jobs/new.html.erb
<div class="container">
  <div>
    <h1 class="col-1"><%= VacuancyJob.human_attribute_name('create') %></h1>
    <h1 class="col-4"><%= VacuancyJob.model_name.human %></h1>
  </div>

  <div class="d-flex p-2">
    <%= form_with model: @vacuancy_job, local: :true do |f| %>
      <div class="form-group">
        <%= f.label :title, VacuancyJob.human_attribute_name('title') %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, VacuancyJob.human_attribute_name('description') %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :ability_description, VacuancyJob.human_attribute_name('ability_description') %>
        <%= f.text_area :ability_description, class: "form-control" %>
      </div>

      <div>
        <p><%= VacuancyJob.human_attribute_name('salary') %></p>

        <div class="d-flex flex-row bd-highlight">
          <div class="form-group">
            <%= f.label :initial_salary, VacuancyJob.human_attribute_name('initial_salary') %>
            <%= f.number_field :initial_salary, class: "form-control" %>
          </div>

          <div class="col-auto">
            <div class="form-group">
              <%= f.label :end_salary, VacuancyJob.human_attribute_name('end_salary') %>
              <%= f.number_field :end_salary, class: "form-control" %>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :level, VacuancyJob.human_attribute_name('level') %>
        <%= f.select :level, @level_selection, {}, {class: "form-control"} %>
      </div>

      <div class="form-group">
        <%= f.label :limit_date, VacuancyJob.human_attribute_name('limit_date') %>
        <%= f.date_field :limit_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :addresse, VacuancyJob.human_attribute_name('addresse') %>
        <%= f.text_field :addresse, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit VacuancyJob.human_attribute_name('create'), class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <br/>
    <%= link_to Profile.human_attribute_name('back'), :back, class: "btn btn-dark" %>
  </div>
</div>

app/views/vacuancy_jobs/search_candidate.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="display-3">Minhas inscrições</h1>
    <br/>
  </div>

  <div class="row">
    <div class="col-sm-5">
      <% @job_applications.each do |vacuancy| %>
        <div class="card">
          <div class="card-body">
            <h3 class="card-title"><%= link_to vacuancy.vacuancy_job.title, vacuancy_job_path(vacuancy.vacuancy_job) %></h3>
            <p class="card-text"><%= vacuancy.vacuancy_job.description %></p>
            <h4 class="card-title"><%= JobApplication.human_attribute_name('comment') %></h4>
            <p class="card-text"><%= vacuancy.comment %></p>
          </div>
        </div>
        <br/>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <br/>
    <%= link_to Profile.human_attribute_name('back'), :back, class: "btn btn-dark" %>
  </div>
</div>

app/views/vacuancy_jobs/search_headhunter.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="display-3">Minhas vagas</h1>
    <br/>
  </div>

  <%= render partial: 'vagas' %>

  <div class="actions">
    <br/>
    <%= link_to Profile.human_attribute_name('back'), :back, class: "btn btn-dark" %>
  </div>
</div>

app/views/vacuancy_jobs/show.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="display-3"><%= VacuancyJob.model_name.human %></h1>
    <h2><%= @vacuancy_job.title %></h2>
    <br/>
  </div>

  <div>
    <h4><%= VacuancyJob.human_attribute_name("status.#{@vacuancy_job.status}") %></h4>
  </div>

  <div class="d-flex p-2">
    <dl class="row">
      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('title') %></dt>
      <dd class="col-sm-9"><%= @vacuancy_job.title %></dd>

      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('description') %></dt>
      <dd class="col-sm-9"><%= @vacuancy_job.description %></dd>

      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('ability_description') %></dt>
      <dd class="col-sm-9"><%= @vacuancy_job.ability_description %></dd>

      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('salary') %></dt>
      <dd class="col-sm-9">Entre <%= number_to_currency(@vacuancy_job.initial_salary) %> a <%= 
        number_to_currency(@vacuancy_job.end_salary) %>
      </dd>

      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('level') %></dt>
      <dd class="col-sm-9"><%= @level_selection[@vacuancy_job.level][0] %></dd>

      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('limit_date') %></dt>
      <dd class="col-sm-9"><%= I18n.l @vacuancy_job.limit_date, format: :default %></dd>

      <dt class="col-sm-2"><%= VacuancyJob.human_attribute_name('addresse') %></dt>
      <dd class="col-sm-9"><%= @vacuancy_job.addresse %></dd>

      <dt class="col-sm-2">Criado por: </dt>
      <dd class="col-sm-9"><%= @vacuancy_job.user.email %></dd>
    </dl>
  </div>
  
  <div class="actions">
    <% if current_user.id == @vacuancy_job.user_id %>
      <%= link_to Profile.human_attribute_name('edit'), root_path, class: "btn btn-primary" %>

      <% if @vacuancy_job.status == 'active' %>
        <%= link_to VacuancyJob.human_attribute_name('close'), vacuancy_job_path(@vacuancy_job), 
            method: 'patch', 
            class: "btn btn-danger" %>
      <% end %>
    <% end %>

    <% if policy(current_user).user_candidate? %>
      <% if @application == false %>
        <%= link_to JobApplication.human_attribute_name('sign_up'), 
            new_job_application_path(vacuancy_job_id: @vacuancy_job), 
            class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>

  <div class="text-center">
    <br/>
    <h2><%= JobApplication.human_attribute_name('subscribers') %></h2>
    <br/>
  </div>
  
  <div class="row">
    <div class="col-sm-5">
      <% @job_applications.each do |job_application| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= job_application.user.profile.name %></h5>
            <h4 class="card-title"><%= job_application.user.profile.formations %></h4>
            <p class="card-text"><%= job_application.comment %></p>
            <% if job_application.user.comment_of_proposal.present? %>
              <p class="card-text">
                <%= CommentOfProposal.human_attribute_name("status.#{job_application.user.comment_of_proposal[0].status }") %>
              </p>
              <%= link_to Profile.model_name.human, job_application.user.profile, class: "btn btn-info" %>
            <% else %>
              <%= link_to Profile.model_name.human, job_application.user.profile, class: "btn btn-info" %>
              <% if current_user.id == @vacuancy_job.user_id %>
                <%= link_to CommentOfReject.human_attribute_name('reject'), 
                new_vacuancy_job_comment_of_reject_path(@vacuancy_job, user_id: job_application.user_id), 
                class: "btn btn-danger" %>

                <%= link_to CommentOfProposal.human_attribute_name('send_proposal'), 
                new_vacuancy_job_comment_of_proposal_path(@vacuancy_job, user_id: job_application.user_id), 
                class: "btn btn-success" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <br/>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <br/>
    <%= link_to Profile.human_attribute_name('back'), :back, class: "btn btn-dark" %>
  </div>
</div>